### ISSUE TITLE
Please Help - High CPU Usage

### ISSUE THREAD

**Issue by talksik** [antoniodipinto/ikisocket#25]
Sorry to keep bugging you for such a great package and some great work for an open source package @antoniodipinto 

For some reason, there are spikes and plateaus in CPU usage.

Below is the digitalocean app platform insights. I have only one user connection, and there seems to be spikes and then just stays there. Memory is fine and stable. This is when there are websocket connections from one or two clients, but maybe there is no cleanup of some loop?

<img width="1176" alt="Screen Shot 2022-09-12 at 1 24 06 PM" src="https://user-images.githubusercontent.com/19339529/189728331-64d0a399-cf57-4764-a3f6-ed101d6b2e82.png">
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/19339529/189728368-4df0e385-4432-40fc-8eda-f880a4b9339b.png">

**Comment by antoniodipinto** [comment]
Hi @talksik the only real loop that is always running is the 'read' loop that accepts incoming messages. My question here is what happens after the WebSocket spawned the messages? Do you have any database involved? Any other places where the app can load data?

I'm asking because I didn't experienced any issue like that in the past and I'm curios to understand what's going on

**Comment by antoniodipinto** [comment]
Closed for inactivity
